/**
 * The Evidence Pack — what you take away from a video.
 *
 * This is the deliberate replacement for downloading the video, which is RED
 * under the YouTube Developer Policies at every tier. What a viewer actually
 * wants from a lecture is not an MP4 they already had access to; it is the
 * claims, the words behind them, and a way back to the moment. That is a
 * strictly better artifact and it is one we are allowed to produce.
 *
 * Two constraints shape the output, and both are refusals:
 *
 *   1. **A verbatim ceiling.** Quotes are capped per video across the whole
 *      export, so a pack cannot become a transcript by another name. The
 *      dossier requires this cumulatively rather than per response, because a
 *      per-response limit is defeated by asking twice.
 *   2. **No link we cannot stand behind.** A receipt whose timing is unlocated
 *      gets its quote and no jump link. Precision is printed next to the
 *      timestamp, so a reader can see what the number is worth.
 */

import { formatTimestamp, type Receipt, youtubeMomentUrl } from '@/domain/transcript'
import { precisionLabel, precisionOf } from '@/domain/timing'

/**
 * Cumulative verbatim words allowed per video, across the entire pack.
 *
 * A cap on quotation is the difference between citing a work and reproducing
 * it. 900 words is generous for evidence and nowhere near a transcript of even
 * a ten-minute video.
 */
export const MAX_VERBATIM_WORDS = 900

export interface PackVideo {
  readonly videoId: string
  readonly title: string
  readonly channelTitle: string
  readonly durationSec: number
}

export interface PackEntry {
  /** The claim, question, or note this evidence supports. */
  readonly heading: string
  readonly receipt: Receipt
}

export interface PackNote {
  readonly tMs: number
  readonly text: string
}

export interface EvidencePackInput {
  readonly video: PackVideo
  readonly entries: readonly PackEntry[]
  readonly notes?: readonly PackNote[]
  readonly generatedAt: number
}

export interface EvidencePack {
  readonly markdown: string
  /** Verbatim words actually included, after the ceiling was applied. */
  readonly verbatimWords: number
  /** Entries whose quotes were shortened or dropped to stay under the ceiling. */
  readonly truncatedEntries: number
}

function wordCount(text: string): number {
  return text.trim().split(/\s+/).filter(Boolean).length
}

/** Cut a quote to `limit` words, marking the cut so nothing reads as complete. */
function clampWords(text: string, limit: number): string {
  const parts = text.trim().split(/\s+/).filter(Boolean)
  if (parts.length <= limit) return text.trim()
  return `${parts.slice(0, limit).join(' ')} […]`
}

function timestampLine(video: PackVideo, receipt: Receipt): string {
  const at = formatTimestamp(receipt.startMs)
  const precision = precisionLabel(receipt.timing)

  if (precisionOf(receipt.timing) === 'unlocated') {
    // No link. A quote with no time is honest; a link that lands in the wrong
    // sentence is a false citation with a timestamp attached.
    return `*${precision}*`
  }
  return `[${at}](${youtubeMomentUrl(video.videoId, receipt.startMs)}) — *${precision}*`
}

/**
 * Build the pack.
 *
 * Entries are processed in order and the ceiling is spent as it goes, so the
 * evidence a reader asked for first is the evidence that survives intact.
 */
export function buildEvidencePack(input: EvidencePackInput): EvidencePack {
  const { video, entries, notes = [], generatedAt } = input

  const lines: string[] = [
    `# ${video.title}`,
    '',
    `**${video.channelTitle}** · ${formatTimestamp(video.durationSec * 1000)} · ` +
      `[watch](https://www.youtube.com/watch?v=${encodeURIComponent(video.videoId)})`,
    '',
    `Evidence pack generated by VidSense on ${new Date(generatedAt).toISOString().slice(0, 10)}.`,
    '',
    '---',
    '',
  ]

  let budget = MAX_VERBATIM_WORDS
  let used = 0
  let truncated = 0

  if (entries.length === 0) {
    lines.push('_No evidence was collected for this video._', '')
  }

  for (const entry of entries) {
    lines.push(`## ${entry.heading}`, '')

    const full = entry.receipt.quote
    const needed = wordCount(full)

    if (budget <= 0) {
      truncated += 1
      lines.push(
        `${timestampLine(video, entry.receipt)}`,
        '',
        '> _Quote omitted — this pack has reached its quotation limit for this video._',
        '',
      )
      continue
    }

    const quote = needed > budget ? clampWords(full, budget) : full
    if (needed > budget) truncated += 1
    const spent = Math.min(needed, budget)
    budget -= spent
    used += spent

    lines.push(`${timestampLine(video, entry.receipt)}`, '', `> ${quote}`, '')
  }

  if (notes.length > 0) {
    lines.push('---', '', '## Your notes', '')
    for (const note of notes) {
      lines.push(`- **${formatTimestamp(note.tMs)}** — ${note.text.trim()}`)
    }
    lines.push('')
  }

  lines.push(
    '---',
    '',
    '_Timestamps carry the precision shown beside them. VidSense never downloads or stores video or audio; ' +
      'quotations are limited and this pack is not a transcript._',
    '',
  )

  return { markdown: lines.join('\n'), verbatimWords: used, truncatedEntries: truncated }
}
